### ISSUE TITLE
Errors hang Express when redis connectivity is lost with Redis client

### ISSUE THREAD

**Issue by benmcmeen** [rv-kip/express-redis-cache#24]
Thanks for a great module.  The documentation indicates errors should just be emitted and pass through to the route... which seems true if node couldn't connect to Redis at all on startup.  But, if connectivity is lost after initial connection is made... the response is never returned.  Here is my code (I pass around the exported cache objects as middleware to the routes in server.js):

```
'use strict';

var redis = require('redis'),
  constants = require('../constants/constants'),
  logger = require('../utils/logger');

var redisClient;
redisClient = redis.createClient(constants.redisPort, constants.redisHost);
redisClient.auth(constants.redisAuth);

redisClient.on('connect', function () {
  logger.info('Connected to redis... ');
});
redisClient.on('error', function (err) {
  logger.error('Error connecting to redis: ' + err);
});

var _redisCache = require('express-redis-cache')({ prefix: constants.env, client: redisClient, expires: 15 });

_redisCache.on('connected', function () {
  logger.info('Cache is functional...');
});
_redisCache.on('error', function (err) {
  logger.error('Cache error: ' + err);
});

exports.tenSecondCache = _redisCache.route(10);
exports.oneMinuteCache = _redisCache.route(60);
exports.fifteenMinuteCache = _redisCache.route(60*15);
```

It seems that when using a Redis client, once it has problems the error that's emitted to the cache error doesn't allow it to pass through?  I can replicate this locally by cutting off network connectivity after the initial connection.  Is there a way I can let it fall through in this case?

**Comment by co2-git** [comment]
Hey mate,

Thanks for the update! Indeed, there was a flaw in the code. I think I fixed it. Could you checkout master at commit e912f52 and let me know if it works for you. If so, I'll push the update to NPM repo. Thanks for reporting!

**Comment by benmcmeen** [comment]
Thanks... I can catch the disconnected event when it happens now, but it still blocks.  It never passes through to the route after this is emitted?

**Comment by co2-git** [comment]
Well, to understand  this part of the code, it's important to understand the role of the property `connected`.  In the file `lib/ExpressRedisCache.js` have a look at the constructor to see how the `connected` property is implemented: 

- first it is set to false
- then when redis emits a 'connect' event, it is set to true
- but when redis emits an ''end' event, it is set to false

Now to the file `lib/ExpressRedisCache/route.js`. There is this snippet:

```js
if ( self.connected === false ) {
  return next();
}
```

So the express-redis-cache middleware checks for `connected`. If true, it assumes there is a connexion to Redis and proceed with caching mechanism. If false, it calls up `next` middleware.

I'm going to have another look at it this afternoon (I live in Barcelona).

Cheers

**Comment by benmcmeen** [comment]
Thanks... This may be related more to how/when redis client emits - but I still experience blocking for requests in this use case.  When I connect to redis and call a cached route... I definitely see self.connected evaluate to true.  If I kill the connection to redis (making it unreachable on the network), and try to access the route again - self.connected still evaluates to true and blocks.  It's not until another subsequent route request causes redis to try reconnect that "end" is emitted (and the connection property gets set to false).

**Comment by co2-git** [comment]
Thanks for the valuable input @benmcmeen! I'll investigate on redis client itself then. I'll let you know when I hit something!

**Comment by co2-git** [comment]
Probably a far stretch, but I modified the code to this manner:

```js
if ( self.connected === false || self.client.connected === false ) {
  return next();
}
```

Note that I have added a check directly to the client since the redis module also exposes a 'connected' boolean property. On my side, it looks like it's working. Do you want to give it a go also on your side? (commit is master 1386df3)

Cheers

**Comment by benmcmeen** [comment]
I still experienced blocking... I think the crux of the problem is the redis client doesn't end until well after the cache thinks it's connected.  I created a pull request with a proposed change (not the nicest solution)... let me know what you think.  And thanks again for looking at this!

**Comment by co2-git** [comment]
Hey mate, sorry for the delay! I was actually thinking about another way of fixing our problem. `cache.route()` calls `cache.get()`. `cache.get()` will throw if there is no connection. Then the error thrown is basically just emitted.

Instead, what about calling `next()` if `cache.get` throws any error at all? So if there is no live connection, the script rollbacks to use the dynamic page and skip cache altogether.

you can have a look at `lib/ExpressRedisCache/routes.js` line 132[master e9c2222] to see how error is now implemented.

What do you reckon? Would that fix your problem?

Cheers

**Comment by co2-git** [comment]
btw thanks for spotting that disconnected emitted a "OK connected" evenet :+1:

**Comment by kmiyashiro** [comment]
I'm looking into using this module, has this issue been resolved?

**Comment by benmcmeen** [comment]
I haven't had time to circle back on this after my pull request (which is
sort of an edge case) - but I am using this - only slightly modified as in
my pull request, and probably redundant to the author's recent changes - in
production for the past couple of months without issues.  I like it a lot.

I do use a hosted Redis solution, and I have a custom heartbeat that pings
my db every now and then (for reasons outside of this module).

Also, I have a custom piece of middleware, loosely based on the module's
documentation to avoid caching errors.  I do this because my responses are
service responses in JSON, and my client applications really need the error
status codes as well as any pertinent messages.  When an response is
cached, subsequent status codes are 200 - which is sort of correct in terms
of a successful cache response... but ultimately misleading since the
status code is often needed to make other choices in the client.

The module has been really useful to me, and I hope this information is
helpful to you.

**Comment by kmiyashiro** [comment]
Cool, thanks for the rundown. I'll give it a shot.

**Comment by rv-kip** [comment]
In my current usage of the module, my app does pick up the redis unavailability and the app continues to function, albeit without caching benefit. 

My app sets up `the express-redis-cache` as such

``` js
var ERC = require('express-redis-cache')l
...
var cache_opts = {
    expire  : redis_opts.cache_expiry_seconds,
    host    : redis_opts.redis_host,
    port    : redis_opts.redis_port,
    prefix  : cache_prefix
};
var cache = new ERC(cache_opts);
cache.on('message', function(message){
    logger.info("cache", message);
});
cache.on('error', function(error){
    logger.error("cache", error);
});
```

I'm going to consider this issue resolved. Please let me know if you still see problems.
